server:
  port: 2000
spring:
  application:
    name: zzh-crowd-mysql
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/project_crowd?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: zzhJava2022925
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
logging:
  level:
    com.atguigu.crowd.mapper: debug
    com.atguigu.crowd.test: debug

eureka:
  instance:
    instance-id: 123.56.30.35:${spring.application.name}:2000
    hostname: 123.56.30.35
  client:
    service-url:
      defaultZone: http://43.143.191.224:1000/eureka

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true



