server:
  port: 1000
spring:
  application:
    name: zzh-crowd-eureka

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: 43.143.191.224:1000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#腾讯云43